import * as Sequelize from "sequelize";

export interface AddUserAttributes {
  email: string
  password: string
}

export interface UserAttributes {
  id?: number;              // id is an auto-generated UUID (by sequelize)
  email: string;
  password: string;
  createdAt?: string;       // autogenerated by sequelize
  updatedAt?: string;       // autogenerated by sequelize
}

export type UserInstance = Sequelize.Instance<UserAttributes> & UserAttributes;

export default (sequalize: Sequelize.Sequelize) => {
  const attributes: SequelizeAttributes<UserAttributes> = {
    id: { type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true },
    email: { type: Sequelize.STRING, allowNull: false },
    password: { type: Sequelize.STRING, allowNull: false },
  };
  return sequalize.define<UserInstance, UserAttributes>("User", attributes);
};
